### ISSUE TITLE
Segfault deep in bfd

### ISSUE THREAD

**Issue by bmario** [tud-zih-energy/lo2s#186]
When I try to run lo2s on taurus, it segfaults deep in libbfd

```
(gdb) r
Starting program: /home/h6/s9242987/Software/lo2s/build/./lo2s -- sleep 10
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[Detaching after fork from child process 13265]
[10746532036326831][pid: 13260][tid: 13260][ WARN]: You requested kernel sampling, but kernel.perf_event_paranoid > 1, retrying without kernel samples.
[10746532036347115][pid: 13260][tid: 13260][ WARN]: To solve this warning you can do one of the following:
[10746532036352442][pid: 13260][tid: 13260][ WARN]:  * sysctl kernel.perf_event_paranoid=1
[10746532036356932][pid: 13260][tid: 13260][ WARN]:  * run lo2s as root
[10746532036361374][pid: 13260][tid: 13260][ WARN]:  * run with --no-kernel to disable kernel space sampling in the first place,
[New Thread 0x7ffff66e7700 (LWP 13266)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff66e7700 (LWP 13266)]
0x00000000005751cb in bfd_hash_lookup ()
Missing separate debuginfos, use: debuginfo-install glibc-2.17-317.el7.x86_64
(gdb) bt
#0  0x00000000005751cb in bfd_hash_lookup ()
#1  0x0000000000600103 in bfd_link_hash_lookup ()
#2  0x00000000005b8b36 in bfd_elf_define_start_stop ()
#3  0x0000000000499c5e in lo2s::bfdr::Lib::read_symbols() ()
#4  0x000000000049a0a9 in lo2s::bfdr::Lib::Lib(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#5  0x00000000004a192f in std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, lo2s::BfdRadareBinary>, true>* std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, lo2s::BfdRadareBinary>, true> > >::_M_allocate_node<std::piecewise_construct_t const&, std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&> >(std::piecewise_construct_t const&, std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>&&, std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>&&) ()
#6  0x000000000049e939 in lo2s::MemoryMap::mmap(lo2s::RawMemoryMapEntry const&) ()
#7  0x000000000043cf36 in lo2s::monitor::MainMonitor::insert_cached_mmap_events(std::deque<lo2s::RawMemoryMapEntry, std::allocator<lo2s::RawMemoryMapEntry> > const&) ()
#8  0x000000000045cc32 in lo2s::perf::sample::Writer::end() ()
#9  0x00000000004456c5 in lo2s::monitor::ThreadedMonitor::thread_main() ()
#10 0x00000000006c472f in execute_native_thread_routine ()
#11 0x00007ffff76c0ea5 in start_thread () from /lib64/libpthread.so.0
#12 0x00007ffff73e996d in clone () from /lib64/libc.so.6
(gdb)
```

```
bash-4.2$ ml

Currently Loaded Modules:
  1) modenv/scs5                 (S)   3) GCC/8.2.0-2.30   5) ncurses/6.1-GCCcore-8.3.0   7) bzip2/1.0.8-GCCcore-8.3.0   9) CMake/3.15.3-GCCcore-8.3.0
  2) binutils/2.30-GCCcore-8.2.0       4) GCCcore/8.3.0    6) zlib/1.2.11-GCCcore-8.3.0   8) cURL/7.66.0-GCCcore-8.3.0  10) OTF2/2.2-GCCcore-8.3.0

  Where:
   S:  Module is Sticky, requires --force to unload or purge

**Comment by bmario** [comment]
Nvm. this seems to be an issue with the broken module system. Probably something like using old Binutils mixed within the CMake cache vs. what the currently loaded modules actually are. I wasn't able to reproduce this with clean build directories and a sane module selection 🤷
